name = "MumzelCode"
uuid = "2d00372c-c190-492a-867f-43c797d38eeb"
version = "0.1.0"
authors = ["Pierre Abbat <phma@bezitopo.org>"]

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1.17.0"
